version: '3'
services: 
  you-db:
    image: neo4j:3.2
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes: 
      - ./db_data:/db_data
    restart: always
  you-web: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
      - 9393:9393
    environment:
      - HOST_URL:localhost
      - DB_URL:localhost
      - DB_PORT:7693
    depends_on:
      - you-db
    tty: true
    volumes:
      - .:/you
    restart: always
volumes:
  db_data:
    external: true